import { SpriteConfig } from "./common";

export const getFemaleSpriteConfig = (colors: any): SpriteConfig => {
  return {
    standing: {
      map: [
        [undefined, undefined, undefined, undefined, undefined],
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [undefined, colors.hair, colors.skin.base, colors.hair, undefined],
        [undefined, colors.hair, colors.skin.base, colors.hair, undefined],
        [
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
        ],
        [
          colors.skin.base,
          colors.breast,
          colors.skin.base,
          colors.breast,
          colors.skin.base,
        ],
        [
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [undefined, colors.skin.base, undefined, colors.skin.base, undefined],
        [undefined, colors.skin.base, undefined, colors.skin.base, undefined],
      ],
      // anchor point is neck
      anchor: {
        x: 3,
        y: 4,
      },
      alias: ["moveSouth1", "moveSouth3", "moveSouth7"],
    },
    moveSouth2: {
      map: [
        [undefined, undefined, undefined, undefined, undefined],
        [undefined, undefined, undefined, undefined, undefined],
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [undefined, colors.hair, colors.skin.base, colors.hair, undefined],
        [undefined, colors.hair, colors.skin.base, colors.hair, undefined],
        [
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
        ],
        [
          colors.skin.base,
          colors.breast,
          colors.skin.base,
          colors.breast,
          colors.skin.base,
        ],
        [
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [undefined, colors.skin.base, undefined, colors.skin.base, undefined],
      ],
      anchor: {
        x: 3,
        y: 4,
      },
      alias: ["moveSouth8"],
    },
    moveSouth4: {
      map: [
        [undefined, undefined, colors.hair, undefined, undefined],
        [undefined, colors.hair, colors.skin.base, colors.hair, undefined],
        [undefined, colors.hair, colors.skin.base, colors.hair, undefined],
        [
          colors.skin.distant1,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
        ],
        [
          colors.skin.distant2,
          colors.breast,
          colors.skin.base,
          colors.breast,
          colors.skin.close,
        ],
        [
          colors.skin.distant2,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.close,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [
          undefined,
          colors.skin.base,
          undefined,
          colors.skin.distant2,
          undefined,
        ],
        [
          undefined,
          colors.skin.base,
          undefined,
          colors.skin.distant2,
          undefined,
        ],
        [undefined, undefined, undefined, colors.skin.distant2, undefined],
      ],
      anchor: {
        x: 3,
        y: 4,
      },
    },
    moveSouth5: {
      map: [
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [undefined, colors.hair, colors.skin.base, colors.hair, undefined],
        [undefined, colors.hair, colors.skin.base, colors.hair, undefined],
        [
          colors.skin.distant1,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.close,
        ],
        [
          colors.skin.distant2,
          colors.breast,
          colors.skin.base,
          colors.breast,
          colors.skin.close,
        ],
        [
          colors.skin.distant2,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [
          undefined,
          colors.skin.close,
          undefined,
          colors.skin.distant2,
          undefined,
        ],
        [
          undefined,
          colors.skin.base,
          undefined,
          colors.skin.distant2,
          undefined,
        ],
        [undefined, undefined, undefined, colors.skin.distant3, undefined],
      ],
      anchor: {
        x: 3,
        y: 4,
      },
    },
    moveSouth6: {
      map: [
        [undefined, undefined, colors.hair, undefined, undefined],
        [undefined, colors.hair, colors.skin.base, colors.hair, undefined],
        [undefined, colors.hair, colors.skin.base, colors.hair, undefined],
        [undefined, undefined, colors.skin.base, undefined, undefined],
        [
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
        ],
        [
          colors.skin.distant1,
          colors.breast,
          colors.skin.base,
          colors.breast,
          colors.skin.close,
        ],
        [
          colors.skin.distant1,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [undefined, colors.skin.base, undefined, colors.skin.base, undefined],
        [undefined, colors.skin.base, undefined, colors.skin.base, undefined],
      ],
      anchor: {
        x: 3,
        y: 5,
      },
    },
    moveSouth9: {
      map: [
        [undefined, undefined, colors.hair, undefined, undefined],
        [undefined, colors.hair, colors.skin.base, colors.hair, undefined],
        [undefined, colors.hair, colors.skin.base, colors.hair, undefined],
        [
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.distant1,
        ],
        [
          colors.skin.close,
          colors.breast,
          colors.skin.base,
          colors.breast,
          colors.skin.distant2,
        ],
        [
          colors.skin.close,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.distant2,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [
          undefined,
          colors.skin.distant2,
          undefined,
          colors.skin.base,
          undefined,
        ],
        [
          undefined,
          colors.skin.distant2,
          undefined,
          colors.skin.base,
          undefined,
        ],
        [undefined, colors.skin.distant2, undefined, undefined, undefined],
      ],
      anchor: {
        x: 3,
        y: 4,
      },
    },
    moveSouth10: {
      map: [
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [undefined, colors.hair, colors.skin.base, colors.hair, undefined],
        [undefined, colors.hair, colors.skin.base, colors.hair, undefined],
        [
          colors.skin.close,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.distant1,
        ],
        [
          colors.skin.close,
          colors.breast,
          colors.skin.base,
          colors.breast,
          colors.skin.distant2,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.distant2,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [
          undefined,
          colors.skin.distant2,
          undefined,
          colors.skin.close,
          undefined,
        ],
        [
          undefined,
          colors.skin.distant2,
          undefined,
          colors.skin.base,
          undefined,
        ],
        [undefined, colors.skin.distant3, undefined, undefined, undefined],
      ],
      anchor: {
        x: 3,
        y: 4,
      },
    },
    moveSouth11: {
      map: [
        [undefined, undefined, colors.hair, undefined, undefined],
        [undefined, colors.hair, colors.skin.base, colors.hair, undefined],
        [undefined, colors.hair, colors.skin.base, colors.hair, undefined],
        [undefined, undefined, colors.skin.base, undefined, undefined],
        [
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
        ],
        [
          colors.skin.close,
          colors.breast,
          colors.skin.base,
          colors.breast,
          colors.skin.distant1,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.distant1,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [undefined, colors.skin.base, undefined, colors.skin.base, undefined],
        [undefined, colors.skin.base, undefined, colors.skin.base, undefined],
      ],
      anchor: {
        x: 3,
        y: 5,
      },
    },
  };
};
