import { SpriteConfig } from "../utils/common";

export const getFemale = (colors: any): SpriteConfig => {
  return {
    standing: {
      map: [
        [undefined, undefined, undefined, undefined, undefined],
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [undefined, colors.hair, colors.skin.base, colors.hair, undefined],
        [undefined, colors.hair, colors.skin.base, colors.hair, undefined],
        [
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
        ],
        [
          colors.skin.base,
          colors.breast,
          colors.skin.base,
          colors.breast,
          colors.skin.base,
        ],
        [
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [undefined, colors.skin.base, undefined, colors.skin.base, undefined],
        [undefined, colors.skin.base, undefined, colors.skin.base, undefined],
      ],
      alias: ["moveSouth1", "moveSouth3", "moveSouth7"],
    },
    moveSouth2: {
      map: [
        [undefined, undefined, undefined, undefined, undefined],
        [undefined, undefined, undefined, undefined, undefined],
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [undefined, colors.hair, colors.skin.base, colors.hair, undefined],
        [undefined, colors.hair, colors.skin.base, colors.hair, undefined],
        [
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
        ],
        [
          colors.skin.base,
          colors.breast,
          colors.skin.base,
          colors.breast,
          colors.skin.base,
        ],
        [
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [undefined, colors.skin.base, undefined, colors.skin.base, undefined],
      ],
      alias: ["moveSouth8"],
    },
    moveSouth4: {
      map: [
        [undefined, undefined, colors.hair, undefined, undefined],
        [undefined, colors.hair, colors.skin.base, colors.hair, undefined],
        [undefined, colors.hair, colors.skin.base, colors.hair, undefined],
        [
          colors.skin.distant1,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
        ],
        [
          colors.skin.distant2,
          colors.breast,
          colors.skin.base,
          colors.breast,
          colors.skin.close,
        ],
        [
          colors.skin.distant2,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.close,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [
          undefined,
          colors.skin.base,
          undefined,
          colors.skin.distant2,
          undefined,
        ],
        [
          undefined,
          colors.skin.base,
          undefined,
          colors.skin.distant2,
          undefined,
        ],
        [undefined, undefined, undefined, colors.skin.distant2, undefined],
      ],
    },
    moveSouth5: {
      map: [
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [undefined, colors.hair, colors.skin.base, colors.hair, undefined],
        [undefined, colors.hair, colors.skin.base, colors.hair, undefined],
        [
          colors.skin.distant1,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.close,
        ],
        [
          colors.skin.distant2,
          colors.breast,
          colors.skin.base,
          colors.breast,
          colors.skin.close,
        ],
        [
          colors.skin.distant2,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [
          undefined,
          colors.skin.close,
          undefined,
          colors.skin.distant2,
          undefined,
        ],
        [
          undefined,
          colors.skin.base,
          undefined,
          colors.skin.distant2,
          undefined,
        ],
        [undefined, undefined, undefined, colors.skin.distant3, undefined],
      ],
    },
    moveSouth6: {
      map: [
        [undefined, undefined, colors.hair, undefined, undefined],
        [undefined, colors.hair, colors.skin.base, colors.hair, undefined],
        [undefined, colors.hair, colors.skin.base, colors.hair, undefined],
        [undefined, undefined, colors.skin.base, undefined, undefined],
        [
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
        ],
        [
          colors.skin.distant1,
          colors.breast,
          colors.skin.base,
          colors.breast,
          colors.skin.close,
        ],
        [
          colors.skin.distant1,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [undefined, colors.skin.base, undefined, colors.skin.base, undefined],
        [undefined, colors.skin.base, undefined, colors.skin.base, undefined],
      ],
    },
    moveSouth9: {
      map: [
        [undefined, undefined, colors.hair, undefined, undefined],
        [undefined, colors.hair, colors.skin.base, colors.hair, undefined],
        [undefined, colors.hair, colors.skin.base, colors.hair, undefined],
        [
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.distant1,
        ],
        [
          colors.skin.close,
          colors.breast,
          colors.skin.base,
          colors.breast,
          colors.skin.distant2,
        ],
        [
          colors.skin.close,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.distant2,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [
          undefined,
          colors.skin.distant2,
          undefined,
          colors.skin.base,
          undefined,
        ],
        [
          undefined,
          colors.skin.distant2,
          undefined,
          colors.skin.base,
          undefined,
        ],
        [undefined, colors.skin.distant2, undefined, undefined, undefined],
      ],
    },
    moveSouth10: {
      map: [
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [undefined, colors.hair, colors.skin.base, colors.hair, undefined],
        [undefined, colors.hair, colors.skin.base, colors.hair, undefined],
        [
          colors.skin.close,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.distant1,
        ],
        [
          colors.skin.close,
          colors.breast,
          colors.skin.base,
          colors.breast,
          colors.skin.distant2,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.distant2,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [
          undefined,
          colors.skin.distant2,
          undefined,
          colors.skin.close,
          undefined,
        ],
        [
          undefined,
          colors.skin.distant2,
          undefined,
          colors.skin.base,
          undefined,
        ],
        [undefined, colors.skin.distant3, undefined, undefined, undefined],
      ],
    },
    moveSouth11: {
      map: [
        [undefined, undefined, colors.hair, undefined, undefined],
        [undefined, colors.hair, colors.skin.base, colors.hair, undefined],
        [undefined, colors.hair, colors.skin.base, colors.hair, undefined],
        [undefined, undefined, colors.skin.base, undefined, undefined],
        [
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
        ],
        [
          colors.skin.close,
          colors.breast,
          colors.skin.base,
          colors.breast,
          colors.skin.distant1,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.distant1,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [undefined, colors.skin.base, undefined, colors.skin.base, undefined],
        [undefined, colors.skin.base, undefined, colors.skin.base, undefined],
      ],
    },
    moveSouthWest1: {
      map: [
        [undefined, undefined, undefined, undefined, undefined],
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [undefined, colors.skin.base, colors.hair, colors.hair, undefined],
        [undefined, colors.skin.base, colors.hair, undefined, undefined],
        [
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
        ],
        [
          colors.skin.base,
          colors.breast,
          colors.skin.base,
          colors.breast,
          colors.skin.base,
        ],
        [
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [undefined, colors.skin.base, undefined, colors.skin.base, undefined],
        [undefined, colors.skin.base, undefined, colors.skin.base, undefined],
      ],
      alias: ["moveSouthWest7"],
    },
    moveSouthWest2: {
      map: [
        [undefined, undefined, undefined, undefined, undefined],
        [undefined, undefined, undefined, undefined, undefined],
        [undefined, colors.hair, colors.hair, undefined, undefined],
        [undefined, colors.skin.base, colors.hair, colors.hair, undefined],
        [undefined, colors.skin.base, colors.hair, colors.hair, undefined],
        [
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
        ],
        [
          colors.skin.base,
          colors.breast,
          colors.skin.base,
          colors.breast,
          colors.skin.base,
        ],
        [
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [undefined, colors.skin.base, undefined, colors.skin.base, undefined],
      ],
    },
    moveSouthWest3: {
      map: [
        [undefined, undefined, undefined, undefined, undefined],
        [undefined, colors.hair, colors.hair, undefined, undefined],
        [undefined, colors.skin.base, colors.hair, colors.hair, undefined],
        [undefined, colors.skin.base, colors.hair, colors.hair, undefined],
        [
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
        ],
        [
          colors.skin.base,
          colors.breast,
          colors.skin.base,
          colors.breast,
          colors.skin.base,
        ],
        [
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [undefined, colors.skin.base, undefined, colors.skin.base, undefined],
        [undefined, colors.skin.base, undefined, colors.skin.base, undefined],
      ],
      alias: ["moveSouthWest9"],
    },
    moveSouthWest4: {
      map: [
        [undefined, colors.hair, colors.hair, undefined, undefined],
        [undefined, colors.skin.base, colors.hair, undefined, undefined],
        [undefined, colors.skin.base, colors.hair, colors.hair, undefined],
        [
          colors.skin.distant1,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
        ],
        [
          colors.skin.distant2,
          colors.breast,
          colors.skin.base,
          colors.breast,
          colors.skin.close,
        ],
        [
          colors.skin.distant2,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.close,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [
          undefined,
          colors.skin.base,
          undefined,
          colors.skin.distant2,
          undefined,
        ],
        [
          undefined,
          colors.skin.base,
          undefined,
          colors.skin.distant2,
          undefined,
        ],
        [undefined, undefined, undefined, colors.skin.distant2, undefined],
      ],
    },
    moveSouthWest5: {
      map: [
        [undefined, colors.hair, colors.hair, undefined, undefined],
        [undefined, colors.skin.base, colors.hair, colors.hair, undefined],
        [undefined, colors.skin.base, colors.hair, colors.hair, undefined],
        [
          colors.skin.distant1,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.close,
        ],
        [
          colors.skin.distant2,
          colors.breast,
          colors.skin.base,
          colors.breast,
          colors.skin.close,
        ],
        [
          colors.skin.distant2,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [
          undefined,
          colors.skin.close,
          undefined,
          colors.skin.distant2,
          undefined,
        ],
        [
          undefined,
          colors.skin.base,
          undefined,
          colors.skin.distant2,
          undefined,
        ],
        [undefined, undefined, undefined, colors.skin.distant3, undefined],
      ],
    },
    moveSouthWest6: {
      map: [
        [undefined, undefined, undefined, undefined, undefined],
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [undefined, colors.skin.base, colors.hair, colors.hair, undefined],
        [undefined, colors.skin.base, colors.hair, undefined, undefined],
        [
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
        ],
        [
          colors.skin.distant1,
          colors.breast,
          colors.skin.base,
          colors.breast,
          colors.skin.close,
        ],
        [
          colors.skin.distant1,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [undefined, colors.skin.base, undefined, colors.skin.base, undefined],
        [undefined, colors.skin.base, undefined, colors.skin.base, undefined],
      ],
    },
    moveSouthWest8: {
      map: [
        [undefined, undefined, undefined, undefined, undefined],
        [undefined, undefined, undefined, undefined, undefined],
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [undefined, colors.skin.base, colors.hair, colors.hair, undefined],
        [undefined, colors.skin.base, colors.hair, undefined, undefined],
        [
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
        ],
        [
          colors.skin.base,
          colors.breast,
          colors.skin.base,
          colors.breast,
          colors.skin.base,
        ],
        [
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [undefined, colors.skin.base, undefined, colors.skin.base, undefined],
      ],
    },
    moveSouthWest10: {
      map: [
        [undefined, colors.hair, colors.hair, undefined, undefined],
        [undefined, colors.skin.base, colors.hair, colors.hair, undefined],
        [undefined, colors.skin.base, colors.hair, colors.hair, undefined],
        [
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.distant1,
        ],
        [
          colors.skin.close,
          colors.breast,
          colors.skin.base,
          colors.breast,
          colors.skin.distant2,
        ],
        [
          colors.skin.close,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.distant2,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [
          undefined,
          colors.skin.distant2,
          undefined,
          colors.skin.base,
          undefined,
        ],
        [
          undefined,
          colors.skin.distant2,
          undefined,
          colors.skin.base,
          undefined,
        ],
        [undefined, colors.skin.distant2, undefined, undefined, undefined],
      ],
    },
    moveSouthWest11: {
      map: [
        [undefined, colors.hair, colors.hair, undefined, undefined],
        [undefined, colors.skin.base, colors.hair, colors.hair, undefined],
        [undefined, colors.skin.base, colors.hair, colors.hair, undefined],
        [
          colors.skin.close,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.distant1,
        ],
        [
          colors.skin.close,
          colors.breast,
          colors.skin.base,
          colors.breast,
          colors.skin.distant2,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.distant2,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [
          undefined,
          colors.skin.distant2,
          undefined,
          colors.skin.close,
          undefined,
        ],
        [
          undefined,
          colors.skin.distant2,
          undefined,
          colors.skin.base,
          undefined,
        ],
        [undefined, colors.skin.distant3, undefined, undefined, undefined],
      ],
    },
    moveSouthWest12: {
      map: [
        [undefined, undefined, colors.hair, colors.hair, undefined],
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [undefined, colors.skin.base, colors.hair, colors.hair, undefined],
        [undefined, colors.skin.base, colors.hair, undefined, undefined],
        [
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
        ],
        [
          colors.skin.close,
          colors.breast,
          colors.skin.base,
          colors.breast,
          colors.skin.distant1,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.distant1,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [undefined, colors.skin.base, undefined, colors.skin.base, undefined],
        [undefined, colors.skin.base, undefined, colors.skin.base, undefined],
      ],
    },
    moveWest1: {
      map: [
        [undefined, undefined, undefined, undefined, undefined],
        [undefined, colors.hair, colors.hair, undefined, undefined],
        [undefined, colors.skin.base, colors.hair, colors.hair, undefined],
        [undefined, colors.skin.base, colors.hair, colors.hair, undefined],
        [
          colors.skin.distant1,
          colors.breast,
          colors.skin.base,
          colors.skin.close,
          undefined,
        ],
        [
          colors.skin.distant1,
          colors.skin.base,
          colors.skin.base,
          colors.skin.close,
          undefined,
        ],
        [
          colors.skin.distant1,
          colors.skin.base,
          colors.skin.base,
          colors.skin.close,
          undefined,
        ],
        [
          undefined,
          colors.skin.distant1,
          colors.skin.base,
          undefined,
          undefined,
        ],
        [
          undefined,
          colors.skin.distant1,
          colors.skin.base,
          undefined,
          undefined,
        ],
        [
          undefined,
          colors.skin.distant1,
          colors.skin.base,
          undefined,
          undefined,
        ],
      ],
    },
    moveWest2: {
      map: [
        [undefined, undefined, undefined, undefined, undefined],
        [undefined, colors.hair, colors.hair, undefined, undefined],
        [undefined, colors.skin.base, colors.hair, colors.hair, undefined],
        [undefined, colors.skin.base, colors.hair, colors.hair, undefined],
        [
          colors.skin.distant1,
          colors.breast,
          colors.skin.base,
          colors.skin.close,
          undefined,
        ],
        [
          colors.skin.distant1,
          colors.skin.base,
          colors.skin.base,
          colors.skin.close,
          undefined,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.close,
          undefined,
        ],
        [
          colors.skin.distant1,
          colors.skin.distant1,
          colors.skin.base,
          undefined,
          undefined,
        ],
        [
          colors.skin.distant1,
          undefined,
          colors.skin.base,
          undefined,
          undefined,
        ],
        [undefined, undefined, colors.skin.base, undefined, undefined],
      ],
    },
    moveWest3: {
      map: [
        [undefined, colors.hair, colors.hair, undefined, undefined],
        [undefined, colors.skin.base, colors.hair, undefined, undefined],
        [undefined, colors.skin.base, colors.hair, colors.hair, undefined],
        [
          colors.skin.distant1,
          colors.breast,
          colors.skin.base,
          colors.skin.close,
          undefined,
        ],
        [
          colors.skin.distant1,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.close,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          undefined,
          colors.skin.close,
        ],
        [undefined, colors.skin.base, colors.skin.base, undefined, undefined],
        [
          colors.skin.distant1,
          undefined,
          colors.skin.base,
          undefined,
          undefined,
        ],
        [
          colors.skin.distant1,
          undefined,
          colors.skin.base,
          undefined,
          undefined,
        ],
        [undefined, undefined, colors.skin.base, undefined, undefined],
      ],
    },
    moveWest4: {
      map: [
        [undefined, colors.hair, colors.hair, undefined, undefined],
        [undefined, colors.skin.base, colors.hair, colors.hair, undefined],
        [undefined, colors.skin.base, colors.hair, colors.hair, undefined],
        [
          colors.skin.distant1,
          colors.breast,
          colors.skin.base,
          colors.skin.close,
          undefined,
        ],
        [
          colors.skin.distant1,
          colors.skin.base,
          colors.skin.base,
          colors.skin.close,
          undefined,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.close,
          undefined,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [
          undefined,
          colors.skin.distant1,
          undefined,
          colors.skin.base,
          undefined,
        ],
        [
          colors.skin.distant1,
          undefined,
          undefined,
          colors.skin.base,
          undefined,
        ],
        [
          colors.skin.distant1,
          undefined,
          undefined,
          colors.skin.base,
          undefined,
        ],
      ],
    },
    moveWest5: {
      map: [
        [undefined, undefined, colors.hair, colors.hair, undefined],
        [undefined, colors.skin.hair, colors.hair, colors.hair, undefined],
        [undefined, colors.skin.base, colors.hair, colors.hair, undefined],
        [undefined, colors.skin.base, colors.skin.base, undefined, undefined],
        [
          colors.skin.base,
          colors.breast,
          colors.skin.base,
          colors.skin.close,
          undefined,
        ],
        [
          colors.skin.distant1,
          colors.skin.base,
          colors.skin.base,
          colors.skin.close,
          undefined,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.close,
          colors.skin.base,
          undefined,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [
          undefined,
          colors.skin.distant1,
          undefined,
          colors.skin.base,
          undefined,
        ],
        [
          undefined,
          colors.skin.distant1,
          undefined,
          undefined,
          colors.skin.base,
        ],
      ],
    },
    moveWest6: {
      map: [
        [undefined, undefined, colors.hair, colors.hair, undefined],
        [undefined, undefined, colors.skin.base, colors.hair, colors.hair],
        [undefined, undefined, colors.skin.base, colors.hair, colors.hair],
        [
          undefined,
          colors.skin.distant1,
          colors.breast,
          colors.skin.base,
          colors.skin.close,
        ],
        [
          undefined,
          colors.skin.distant1,
          colors.skin.base,
          colors.skin.base,
          colors.skin.close,
        ],
        [
          undefined,
          colors.skin.distant1,
          colors.skin.base,
          colors.skin.close,
          colors.skin.base,
        ],
        [
          undefined,
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
        ],
        [undefined, undefined, colors.skin.distant1, undefined, undefined],
        [undefined, undefined, undefined, colors.skin.distant1, undefined],
      ],
    },
    moveWest7: {
      map: [
        [undefined, colors.hair, colors.hair, undefined, undefined],
        [undefined, colors.skin.base, colors.hair, undefined, undefined],
        [undefined, colors.skin.base, colors.hair, colors.hair, undefined],
        [
          colors.skin.base,
          colors.breast,
          colors.skin.base,
          colors.skin.close,
          undefined,
        ],
        [
          colors.skin.close,
          colors.skin.base,
          colors.skin.base,
          colors.skin.close,
          undefined,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.close,
          undefined,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [undefined, colors.skin.base, colors.skin.base, undefined, undefined],
        [
          undefined,
          colors.skin.distant1,
          colors.skin.base,
          undefined,
          undefined,
        ],
        [
          undefined,
          undefined,
          colors.skin.base,
          colors.skin.distant1,
          undefined,
        ],
        [
          undefined,
          undefined,
          colors.skin.base,
          colors.skin.distant1,
          undefined,
        ],
      ],
    },
    moveWest8: {
      map: [
        [undefined, undefined, colors.hair, colors.hair, undefined],
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [undefined, colors.skin.base, colors.hair, colors.hair, undefined],
        [undefined, colors.skin.base, colors.skin.base, undefined, undefined],
        [
          colors.skin.close,
          colors.breast,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [
          colors.skin.close,
          colors.skin.base,
          colors.skin.base,
          undefined,
          colors.skin.base,
        ],
        [undefined, colors.skin.base, colors.skin.base, undefined, undefined],
        [
          undefined,
          colors.skin.distant1,
          colors.skin.base,
          undefined,
          undefined,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.distant1,
          undefined,
          undefined,
        ],
        [
          colors.skin.base,
          undefined,
          undefined,
          colors.skin.distant1,
          undefined,
        ],
      ],
    },
    moveWest9: {
      map: [
        [undefined, undefined, undefined, undefined, undefined],
        [undefined, colors.hair, colors.hair, undefined, undefined],
        [undefined, colors.skin.base, colors.hair, undefined, undefined],
        [undefined, colors.skin.base, colors.hair, colors.hair, undefined],
        [
          colors.skin.base,
          colors.breast,
          colors.skin.base,
          colors.skin.close,
          undefined,
        ],
        [
          colors.skin.distant1,
          colors.skin.base,
          colors.skin.base,
          colors.skin.close,
          undefined,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [undefined, colors.skin.base, colors.skin.base, undefined, undefined],
        [
          undefined,
          colors.skin.distant1,
          colors.skin.close,
          undefined,
          undefined,
        ],
        [
          undefined,
          undefined,
          colors.skin.close,
          colors.skin.distant1,
          undefined,
        ],
      ],
    },
    moveNorth1: {
      map: [
        [undefined, undefined, undefined, undefined, undefined],
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [
          colors.skin.base,
          colors.hair,
          colors.hair,
          colors.hair,
          colors.skin.base,
        ],
        [
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
        ],
        [
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [undefined, colors.skin.base, undefined, colors.skin.base, undefined],
        [undefined, colors.skin.base, undefined, colors.skin.base, undefined],
      ],
      alias: ["moveNorth3", "moveNorth7", "moveNorth9"],
    },
    moveNorth2: {
      map: [
        [undefined, undefined, undefined, undefined, undefined],
        [undefined, undefined, undefined, undefined, undefined],
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [
          colors.skin.base,
          colors.hair,
          colors.hair,
          colors.hair,
          colors.skin.base,
        ],
        [
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
        ],
        [
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [undefined, colors.skin.base, undefined, colors.skin.base, undefined],
      ],
      alias: ["moveNorth8"],
    },
    moveNorth4: {
      map: [
        [undefined, undefined, undefined, undefined, undefined],
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [
          colors.skin.base,
          colors.hair,
          colors.hair,
          colors.hair,
          colors.skin.base,
        ],
        [
          colors.skin.close,
          colors.hair,
          colors.hair,
          colors.hair,
          colors.skin.distant1,
        ],
        [
          colors.skin.close,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.distant1,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [
          undefined,
          colors.skin.distant1,
          undefined,
          colors.skin.base,
          undefined,
        ],
        [
          undefined,
          colors.skin.distant1,
          undefined,
          colors.skin.base,
          undefined,
        ],
        [undefined, undefined, undefined, colors.skin.base, undefined],
      ],
    },
    moveNorth5: {
      map: [
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [
          colors.skin.base,
          colors.hair,
          colors.hair,
          colors.hair,
          colors.skin.distant1,
        ],
        [
          colors.skin.close,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.distant1,
        ],
        [
          colors.skin.close,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [
          undefined,
          colors.skin.distant1,
          undefined,
          colors.skin.base,
          undefined,
        ],
        [
          undefined,
          colors.skin.distant2,
          undefined,
          colors.skin.base,
          undefined,
        ],
        [undefined, undefined, undefined, colors.skin.close, undefined],
      ],
    },
    moveNorth6: {
      map: [
        [undefined, undefined, undefined, undefined, undefined],
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [
          colors.skin.base,
          colors.hair,
          colors.hair,
          colors.hair,
          colors.skin.base,
        ],
        [
          colors.skin.close,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.distant1,
        ],
        [
          colors.skin.close,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [undefined, colors.skin.base, undefined, colors.skin.base, undefined],
        [undefined, colors.skin.base, undefined, colors.skin.base, undefined],
      ],
    },
    moveNorth10: {
      map: [
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [
          colors.skin.base,
          colors.hair,
          colors.hair,
          colors.hair,
          colors.skin.base,
        ],
        [
          colors.skin.distant1,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.close,
        ],
        [
          colors.skin.distant1,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.close,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [
          undefined,
          colors.skin.base,
          undefined,
          colors.skin.distant1,
          undefined,
        ],
        [
          undefined,
          colors.skin.base,
          undefined,
          colors.skin.distant1,
          undefined,
        ],
        [undefined, colors.skin.base, undefined, undefined, undefined],
      ],
    },
    moveNorth11: {
      map: [
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [
          colors.skin.distant1,
          colors.hair,
          colors.hair,
          colors.hair,
          colors.skin.base,
        ],
        [
          colors.skin.distant1,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.close,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.close,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [
          undefined,
          colors.skin.base,
          undefined,
          colors.skin.distant1,
          undefined,
        ],
        [
          undefined,
          colors.skin.base,
          undefined,
          colors.skin.distant2,
          undefined,
        ],
        [undefined, colors.skin.close, undefined, undefined, undefined],
      ],
    },
    moveNorth12: {
      map: [
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [undefined, colors.hair, colors.hair, colors.hair, undefined],
        [
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
        ],
        [
          colors.skin.distant1,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.close,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          colors.skin.close,
        ],
        [
          undefined,
          colors.skin.base,
          colors.skin.base,
          colors.skin.base,
          undefined,
        ],
        [undefined, colors.skin.base, undefined, colors.skin.base, undefined],
        [undefined, colors.skin.base, undefined, colors.skin.base, undefined],
      ],
    },
  };
};
